### PR TITLE
feat: implement snapshot listeners

### PR DESCRIPTION
**Pull request by garviand**

### CODE REVIEW

**Comment by garviand** [comment]
Hey @wovalle! I know things have been busy so no rush, but I'm curious what your timeline is for the next release and if this PR seems ready (or almost ready) to you. I'm just realizing now that Travis failed (it seems due to prettier checks) so I'll touch that up in the meantime. If the codecov checks failing is an issue let me know and I'll work on improving those as well.

**Comment by wovalle** [comment]
Hey @garviand! Sorry it took me so long to answer this, I recently had a surgery and was out for a bit.

The next big release was done just now! (https://github.com/wovalle/fireorm/pull/172). It was a much needed update of the metadata lookup and how subcollections are handled, so please rebase. Even though I added (what I think is) a good quantity of tests my next focus is to upgrade fireorm in a prod app just to be sure everything works correctly.

As of this PR, please rebase one last time and I'll do a proper code review! :)

**Comment by garviand** [comment]
@wovalle Hi, sorry for the delay on this. To be honest, I don't have a ton of experience with rebasing so If I need to redo it let me know, but I think it worked well. The only thing that came up was one issue with types which I'm sure we can sort out. I'll make a comment where it is so you can have a look.

**Comment by garviand** [comment]
```
const queryResult: (() => void) | T[]

Element implicitly has an 'any' type because expression of type '0' can't be used to index type '(() => void) | T[]'.
  Property '0' does not exist on type '(() => void) | T[]'.
```

https://github.com/wovalle/fireorm/pull/218/files#diff-ddaef2196a17c69cc1d3167e349d700d3cccf83379816c3e3dd6726ac2dfdd80L186

**Comment by garviand** [comment]
Ok, the solution I went with was casting `queryResult` as `T[]`. Let me know if this isn't what you would do. I have some time in the next week or two to clean this PR up however you see fit.

**Comment by wovalle** [comment]
yeah, casting as `T[]` is good enough!

**Review by wovalle — COMMENTED** [review]
Hey, this is looking quite good for a first version!

Can you fix the linting errors so we can make a release? 

Thanks!

**Comment by wovalle** [comment]
Will merge to another branch and fix the linting issues!

**Pull request merged**
