### PR TITLE
Returning class instance from methods

### PR DESCRIPTION
**Pull request by wovalle**
Returning class instances from methods so models can have getters!

### CODE REVIEW

**Comment by wovalle** [comment]
@all-contributors please add @wovalle for code

**Comment by wovalle** [comment]
@all-contributors please add @wovalle for code

**Comment by wovalle** [comment]
@all-contributors please add @wovalle for code, bug, blog, doc, examples, ideas, infra, review, test

**Comment by jonesnc** [comment]
@wovalle Great work! This looks like a powerful feature, for type checking, etc.

**Pull request merged**
