### PR TITLE
fix: improve the update method types

### PR DESCRIPTION
**Pull request by tomorroN**
fix: improve the update method types following the method functional logic

### CODE REVIEW

**Comment by wovalle** [comment]
Thanks for the PR! Can you update the commit message from feat: to fix:? 

Thanks!

**Comment by tomorroN** [comment]
> Thanks for the PR! Can you update the commit message from feat: to fix:?
> 
> Thanks!

Sure!

**Comment by wovalle** [comment]
Thanks!

**Review by wovalle — APPROVED** [review]

**Comment by wovalle** [comment]
@all-contributors please add @tomorroN for code

**Pull request merged**
