### PR TITLE
feat: Custom query escape hatch

### PR DESCRIPTION
**Pull request by MarZab**
Add an escape hatch to have access to the underlying firebase query.

This is a good way to leave the door open to unsupported features in FireORM.

Similar implementation but with local moneypatching here: https://github.com/wovalle/fireorm/issues/244#issue-847449663

Example for usage here: https://github.com/wovalle/fireorm/issues/244#issuecomment-811512104

### CODE REVIEW

**Comment by wovalle** [comment]
Great job! This definitely breaks the "type-safe" approach of fireorm but gives the user power to use features not yet implemented in fireorm.

Would you mind adding a couple of unit tests?

**Comment by MarZab** [comment]
Sure, will do.

Btw I saw you were working on references, and I had to expose CollectionReference within the customQuery in order to generate them. Let me know if you have a different plan here, I didn't want to impose pattern that will be deprecated soon.

Thanks

**Comment by wovalle** [comment]
Work on References is actually paused, you can proceed!

**Comment by wovalle** [comment]
@all-contributors add @MarZab for code

**Pull request merged**
