### PR TITLE
chore: transactions refactor

### LINKED ISSUE #101: Batch and transaction writes across multiple collections
Is there currently any way to run transactions or batched writes across multiple collections?

Take the following example: when a user deletes their account, any posts that they have made should also be deleted.

The way FireORM currently stands, it looks like there would need to be multiple transactions.

Is there a general rule on how to do this? Would the transactions be nested? Would a nested transaction still succeed and make writes if the parent failed?

### PR DESCRIPTION
**Pull request by wovalle**
Closes #101 

...eventually

### CODE REVIEW

**Comment by joemckie** [comment]
What's the status on this? Anything I can do to help? There's quite a few places in my codebase that needs this functionality so anything I can do to move it along I'm happy to do!

**Comment by wovalle** [comment]
I've been quite busy the past few weeks but after the saturday I'll have time to actually finish this.

I got stuck because before I use to pass the serialization method to the batchs (from the repositories) but now that I can call the batch methods outside a repository that will be no longer possible. I'll get to it next week.

**Comment by wovalle** [comment]
Also, closes #129 #127 #130 #131

**Comment by voxelbusters** [comment]
May I know the status of this feature?

**Comment by manwithsteelnerves** [comment]
May I know the status of this feature?

**Comment by wovalle** [comment]
@manwithsteelnerves Working on it as we speak.

**Pull request merged**
